/* --- Agenda docente --- */
let agendaViewDate = today();
let agendaTab = 'week';
let agendaEditingId = '';
let agendaMonthAnchor = today().slice(0,7);
let cteEditingId = '';
let cteFilterStatus = '';
const AGENDA_TYPES = ['CTE','Calificaciones','Asueto','Reunión','Evaluación','Guardia','Honores','Comisión','Incidencia','Administrativo','Cita con tutor','Recordatorio','Otro'];
const AGENDA_PRIORITIES = ['baja','media','alta','crítica'];
const AGENDA_REPEAT = ['ninguna','diaria','semanal','quincenal','mensual'];
const CTE_TYPES = ['CTE','Academia','Reunión docente','Supervisión','Otro'];
const CTE_STATUSES = ['pendiente','en proceso','cumplido','vencido'];
const CTE_RESPONSIBLE_TYPES = ['Docente','Director','Comité','Grupo','Otro'];
function normalizeAgendaEvent(e={}){ const ev=e&&typeof e==='object'?{...e}:{}; ev.id=ev.id||uid(); ev.title=ev.title||''; ev.type=ev.type||'Recordatorio'; ev.date=ev.date||today(); ev.startTime=ev.startTime||''; ev.endTime=ev.endTime||''; ev.priority=AGENDA_PRIORITIES.includes(ev.priority)?ev.priority:'media'; ev.repeat=AGENDA_REPEAT.includes(ev.repeat)?ev.repeat:'ninguna'; ev.studentId=ev.studentId||''; ev.description=ev.description||''; ev.status=ev.status||'pendiente'; ev.createdAt=ev.createdAt||new Date().toISOString(); ev.updatedAt=ev.updatedAt||ev.createdAt; return ev; }
function normalizeQuickNote(n={}){ const note=n&&typeof n==='object'?{...n}:{}; note.id=note.id||uid(); note.text=note.text||''; note.priority=AGENDA_PRIORITIES.includes(note.priority)?note.priority:'media'; note.createdAt=note.createdAt||new Date().toISOString(); note.updatedAt=note.updatedAt||note.createdAt; return note; }
function ensureAgenda(){ db.group.agenda=Array.isArray(db.group.agenda)?db.group.agenda.map(normalizeAgendaEvent):[]; db.group.quickNotes=Array.isArray(db.group.quickNotes)?db.group.quickNotes.map(normalizeQuickNote):[]; }
function dateAdd(dateStr,days){ const d=new Date(dateStr+'T00:00:00'); d.setDate(d.getDate()+days); return d.toISOString().slice(0,10); }
function monthAdd(dateStr,months){ const d=new Date(dateStr+'T00:00:00'); const day=d.getDate(); d.setMonth(d.getMonth()+months); if(d.getDate()!==day)d.setDate(0); return d.toISOString().slice(0,10); }
function startOfWeek(dateStr){ const d=new Date(dateStr+'T00:00:00'); const day=d.getDay(); const diff=(day===0?-6:1-day); d.setDate(d.getDate()+diff); return d.toISOString().slice(0,10); }
function endOfWeek(dateStr){ return dateAdd(startOfWeek(dateStr),6); }
function formatLongDate(dateStr){ try{ return new Date(dateStr+'T00:00:00').toLocaleDateString('es-MX',{weekday:'long',day:'numeric',month:'long',year:'numeric'}); }catch(e){ return dateStr; } }
function agendaTypeIcon(type){ return ({CTE:'🏫',Calificaciones:'📊',Asueto:'🌴','Reunión':'🤝','Evaluación':'🧪','Guardia':'🛡️','Honores':'🇲🇽','Comisión':'📌','Incidencia':'🚨','Administrativo':'📄','Cita con tutor':'👪','Recordatorio':'🔔','Otro':'📌'})[type]||'📌'; }
function agendaPriorityClass(p){ return ({baja:'prio-low',media:'prio-med',alta:'prio-high','crítica':'prio-critical'})[p]||'prio-med'; }
function agendaPriorityLabel(p){ return p==='crítica'?'Crítica':(p||'media').charAt(0).toUpperCase()+(p||'media').slice(1); }
function agendaOccurrenceFor(ev,date){ return {...ev, occurrenceDate:date, occurrenceKey:ev.id+'@'+date}; }
function agendaOccurrences(start,end){ ensureAgenda(); const out=[]; (db.group.agenda||[]).forEach(raw=>{ const ev=normalizeAgendaEvent(raw); if(ev.repeat==='ninguna'){ if(ev.date>=start&&ev.date<=end) out.push(agendaOccurrenceFor(ev,ev.date)); return; } let cur=ev.date, guard=0; while(cur<=end&&guard<370){ if(cur>=start) out.push(agendaOccurrenceFor(ev,cur)); cur=ev.repeat==='diaria'?dateAdd(cur,1):ev.repeat==='semanal'?dateAdd(cur,7):ev.repeat==='quincenal'?dateAdd(cur,14):ev.repeat==='mensual'?monthAdd(cur,1):end; guard++; } }); return out.sort((a,b)=>(a.occurrenceDate+a.startTime).localeCompare(b.occurrenceDate+b.startTime)); }
function agendaHomeData(){ const t=today(); return { today:agendaOccurrences(t,t).filter(e=>e.status!=='hecho'&&e.status!=='cerrado'), next7:agendaOccurrences(dateAdd(t,1),dateAdd(t,7)).filter(e=>e.status!=='hecho'&&e.status!=='cerrado'), overdue:(db.group.agenda||[]).map(normalizeAgendaEvent).filter(e=>e.date<t&&e.status!=='hecho'&&e.status!=='cerrado').sort((a,b)=>a.date.localeCompare(b.date))}; }
function getHomeStats(){ const rows=db.group.attendance?.[today()]||[]; const total=getActiveStudents().length; const openInc=(db.group.bitacoraReports||[]).filter(r=>buildReportStatus(normalizeBitacoraReport(r))!=='cerrado').length; return {present:rows.length, absent:Math.max(total-rows.length,0), openIncidents:openInc}; }
function renderMiniAgendaItem(ev){ const date=ev.occurrenceDate||ev.date; const student=ev.studentId?` · ${esc(getStudentLabel(ev.studentId))}`:''; return `<div class="mini-agenda-item ${agendaPriorityClass(ev.priority)}"><span>${agendaTypeIcon(ev.type)}</span><div><b>${esc(ev.title||ev.type)}</b><small>${esc(date)} ${esc(ev.startTime||'')}${student}</small></div></div>`; }
function agendaStudentOptions(selected=''){ return `<option value="">Sin vincular alumno</option>`+getActiveStudents().map(s=>`<option value="${s.id}" ${selected===s.id?'selected':''}>${esc(s.listNo||'')} · ${esc(s.name||'')}</option>`).join(''); } // FIX v4: solo activos
function renderAgenda(){ ensureAgenda(); if(agendaTab==='form') return renderAgendaForm(); if(agendaTab==='month') return renderAgendaMonth(); if(agendaTab==='notes') return renderAgendaNotes(); if(agendaTab==='tools') return renderAgendaTools(); return renderAgendaWeek(); }
function renderAgendaTabs(active){ return `<div class="card"><div class="tabs"><button class="tab ${active==='week'?'active':''}" data-agenda-tab="week">Semana</button><button class="tab ${active==='month'?'active':''}" data-agenda-tab="month">Mes</button><button class="tab ${active==='notes'?'active':''}" data-agenda-tab="notes">Notas rápidas</button><button class="tab ${active==='tools'?'active':''}" data-agenda-tab="tools">Importar / Exportar</button></div></div>`; }
function renderAgendaWeek(){ const start=startOfWeek(agendaViewDate), end=endOfWeek(agendaViewDate); const items=agendaOccurrences(start,end); const days=Array.from({length:7},(_,i)=>dateAdd(start,i)); return `${renderAgendaTabs('week')}<div class="card"><div class="agenda-head"><button class="btn secondary" id="ag-prev-week">←</button><div><div class="section-title">Agenda semanal</div><div class="small">${esc(start)} al ${esc(end)}</div></div><button class="btn secondary" id="ag-next-week">→</button></div><div class="row row2"><button class="btn primary" id="ag-new-event">+ Evento / recordatorio</button><button class="btn secondary" id="ag-today">Hoy</button></div></div><div class="week-list">${days.map(d=>{ const dayItems=items.filter(x=>x.occurrenceDate===d); return `<div class="card day-card ${d===today()?'today':''}"><div class="day-title"><b>${esc(formatLongDate(d))}</b><span>${dayItems.length}</span></div>${dayItems.length?dayItems.map(renderAgendaItem).join(''):'<div class="small">Sin eventos.</div>'}</div>`; }).join('')}</div>${renderAgendaQuickNotesCard()}`; }
function renderAgendaMonth(){ const [y,m]=agendaMonthAnchor.split('-').map(Number); const first=new Date(y,m-1,1); const firstStr=first.toISOString().slice(0,10); const start=startOfWeek(firstStr); const last=new Date(y,m,0).toISOString().slice(0,10); const end=endOfWeek(last); const items=agendaOccurrences(start,end); const days=[]; for(let cur=start; cur<=end; cur=dateAdd(cur,1)) days.push(cur); return `${renderAgendaTabs('month')}<div class="card"><div class="agenda-head"><button class="btn secondary" id="ag-prev-month">←</button><div><div class="section-title">Vista mensual</div><div class="small">${agendaMonthAnchor}</div></div><button class="btn secondary" id="ag-next-month">→</button></div><button class="btn primary" id="ag-new-event">+ Evento / recordatorio</button></div><div class="month-grid">${days.map(d=>{ const count=items.filter(x=>x.occurrenceDate===d).length; const other=!d.startsWith(agendaMonthAnchor); return `<button class="month-day ${d===today()?'today':''} ${other?'other':''}" data-month-day="${d}"><b>${Number(d.slice(8,10))}</b>${count?`<span>${count}</span>`:''}</button>`; }).join('')}</div><div class="card"><div class="section-title">Eventos del día seleccionado</div><div id="month-day-detail" class="small">Toca un día para ver sus eventos.</div></div>`; }
function renderAgendaItem(ev){ const student=ev.studentId?`<div class="small">Alumno: ${esc(getStudentLabel(ev.studentId))}</div>`:''; return `<div class="agenda-item ${agendaPriorityClass(ev.priority)}"><div class="agenda-icon">${agendaTypeIcon(ev.type)}</div><div class="agenda-main"><b>${esc(ev.title||ev.type)}</b><div class="small">${esc(ev.type)} · ${esc(agendaPriorityLabel(ev.priority))} · ${esc(ev.startTime||'sin hora')}${ev.endTime?' - '+esc(ev.endTime):''}${ev.repeat&&ev.repeat!=='ninguna'?' · Repite '+esc(ev.repeat):''}</div>${student}${ev.description?`<div class="help">${esc(ev.description)}</div>`:''}</div><div class="agenda-actions"><button class="mini" data-ag-edit="${ev.id}">Editar</button><button class="mini" data-ag-done="${ev.id}">Hecho</button><button class="mini" data-ag-del="${ev.id}">Eliminar</button></div></div>`; }
function renderAgendaQuickNotesCard(){ const notes=(db.group.quickNotes||[]).map(normalizeQuickNote).sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||'')); return `<div class="card"><div class="section-title">Notas rápidas</div><div class="field"><div class="small">Nueva nota</div><textarea id="quick-note-text" rows="3" placeholder="Dicta o escribe una idea rápida. Luego puedes convertirla en recordatorio."></textarea>${micBtn('quick-note-text')}</div><div class="row row2"><select id="quick-note-priority">${AGENDA_PRIORITIES.map(p=>`<option value="${p}">${agendaPriorityLabel(p)}</option>`).join('')}</select><button class="btn primary" id="quick-note-save">Guardar nota</button></div><div style="margin-top:12px">${notes.length?notes.slice(0,8).map(n=>`<div class="agenda-item ${agendaPriorityClass(n.priority)}"><div class="agenda-icon">🗒️</div><div class="agenda-main"><b>${esc(n.text)}</b><div class="small">${agendaPriorityLabel(n.priority)} · ${esc((n.createdAt||'').slice(0,16).replace('T',' '))}</div></div><div class="agenda-actions"><button class="mini" data-note-to-reminder="${n.id}">A recordatorio</button><button class="mini" data-note-del="${n.id}">Eliminar</button></div></div>`).join(''):'<div class="small">Sin notas rápidas.</div>'}</div></div>`; }
function renderAgendaNotes(){ return `${renderAgendaTabs('notes')}${renderAgendaQuickNotesCard()}`; }
function renderAgendaTools(){ return `${renderAgendaTabs('tools')}<div class="card"><div class="section-title">Importar / Exportar agenda</div><div class="row row2"><button class="btn secondary" id="ag-export-xlsx">Exportar Excel</button><button class="btn secondary" id="ag-export-json">Exportar JSON</button><label class="btn primary" style="display:grid;place-items:center"><input id="ag-import-json" type="file" accept=".json,application/json" style="display:none">Importar JSON</label><label class="btn primary" style="display:grid;place-items:center"><input id="ag-import-xlsx" type="file" accept=".xlsx,.xls,.csv" style="display:none">Importar Excel/CSV</label></div><div class="help">Columnas sugeridas: titulo, tipo, fecha, hora_inicio, hora_fin, prioridad, repeticion, alumno, descripcion, estatus.</div></div>`; }
function renderAgendaForm(){ const ev=agendaEditingId?normalizeAgendaEvent((db.group.agenda||[]).find(x=>x.id===agendaEditingId)||{}):normalizeAgendaEvent({date:agendaViewDate}); return `${renderAgendaTabs('form')}<div class="card"><div class="section-title">${agendaEditingId?'Editar evento':'Nuevo evento / recordatorio'}</div><div class="row"><div><div class="small">Título *</div><input id="ag-title" value="${esc(ev.title)}" placeholder="Ej. Entrega de calificaciones"></div><div class="row row2"><div><div class="small">Tipo</div><select id="ag-type">${AGENDA_TYPES.map(t=>`<option ${ev.type===t?'selected':''}>${t}</option>`).join('')}</select></div><div><div class="small">Prioridad</div><select id="ag-priority">${AGENDA_PRIORITIES.map(p=>`<option value="${p}" ${ev.priority===p?'selected':''}>${agendaPriorityLabel(p)}</option>`).join('')}</select></div></div><div class="row row3"><div><div class="small">Fecha *</div><input id="ag-date" type="date" value="${esc(ev.date)}"></div><div><div class="small">Hora inicio</div><input id="ag-start" type="time" value="${esc(ev.startTime)}"></div><div><div class="small">Hora fin</div><input id="ag-end" type="time" value="${esc(ev.endTime)}"></div></div><div class="row row2"><div><div class="small">Repetición</div><select id="ag-repeat">${AGENDA_REPEAT.map(r=>`<option value="${r}" ${ev.repeat===r?'selected':''}>${r}</option>`).join('')}</select></div><div><div class="small">Alumno vinculado</div><select id="ag-student">${agendaStudentOptions(ev.studentId)}</select></div></div><div class="field"><div class="small">Descripción / notas</div><textarea id="ag-description" rows="5" placeholder="Puedes dictar indicaciones, acuerdos o detalles.">${esc(ev.description)}</textarea>${micBtn('ag-description')}</div><div class="row row2"><button class="btn secondary" id="ag-cancel">Cancelar</button><button class="btn primary" id="ag-save">Guardar</button></div></div></div>`; }
function bindAgenda(){ bindMicButtons(); document.querySelectorAll('[data-agenda-tab]').forEach(btn=>btn.onclick=()=>{ agendaTab=btn.dataset.agendaTab; renderCurrentScreen(); }); if(agendaTab==='week') bindAgendaWeek(); if(agendaTab==='month') bindAgendaMonth(); if(agendaTab==='form') bindAgendaForm(); if(agendaTab==='notes') bindAgendaNotes(); if(agendaTab==='tools') bindAgendaTools(); }
function bindAgendaWeek(){ document.getElementById('ag-prev-week')?.addEventListener('click',()=>{agendaViewDate=dateAdd(agendaViewDate,-7);renderCurrentScreen();}); document.getElementById('ag-next-week')?.addEventListener('click',()=>{agendaViewDate=dateAdd(agendaViewDate,7);renderCurrentScreen();}); document.getElementById('ag-today')?.addEventListener('click',()=>{agendaViewDate=today();renderCurrentScreen();}); document.getElementById('ag-new-event')?.addEventListener('click',()=>{agendaEditingId='';agendaTab='form';renderCurrentScreen();}); bindAgendaItemActions(); bindAgendaNotes(); }
function bindAgendaMonth(){ document.getElementById('ag-prev-month')?.addEventListener('click',()=>{agendaMonthAnchor=monthAdd(agendaMonthAnchor+'-01',-1).slice(0,7);renderCurrentScreen();}); document.getElementById('ag-next-month')?.addEventListener('click',()=>{agendaMonthAnchor=monthAdd(agendaMonthAnchor+'-01',1).slice(0,7);renderCurrentScreen();}); document.getElementById('ag-new-event')?.addEventListener('click',()=>{agendaEditingId='';agendaTab='form';renderCurrentScreen();}); document.querySelectorAll('[data-month-day]').forEach(btn=>btn.onclick=()=>{ const d=btn.dataset.monthDay; const items=agendaOccurrences(d,d); document.getElementById('month-day-detail').innerHTML=items.length?items.map(renderAgendaItem).join(''):'Sin eventos.'; bindAgendaItemActions(); }); }
function bindAgendaForm(){ document.getElementById('ag-cancel')?.addEventListener('click',()=>{agendaTab='week';agendaEditingId='';renderCurrentScreen();}); document.getElementById('ag-save')?.addEventListener('click',()=>{ const title=valOf('ag-title').trim(), date=valOf('ag-date'); if(!title||!date){toast('Título y fecha son obligatorios');return;} const ev=normalizeAgendaEvent({id:agendaEditingId||uid(),title,type:valOf('ag-type'),date,startTime:valOf('ag-start'),endTime:valOf('ag-end'),priority:valOf('ag-priority'),repeat:valOf('ag-repeat'),studentId:valOf('ag-student'),description:valOf('ag-description'),status:'pendiente',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}); ensureAgenda(); const idx=db.group.agenda.findIndex(x=>x.id===ev.id); if(idx>=0){ ev.createdAt=db.group.agenda[idx].createdAt||ev.createdAt; db.group.agenda[idx]=ev; } else db.group.agenda.push(ev); if(!saveDb())return; toast('Evento guardado'); agendaViewDate=ev.date; agendaTab='week'; agendaEditingId=''; renderCurrentScreen(); }); }
function bindAgendaItemActions(){ document.querySelectorAll('[data-ag-edit]').forEach(btn=>btn.onclick=()=>{agendaEditingId=btn.dataset.agEdit;agendaTab='form';renderCurrentScreen();}); document.querySelectorAll('[data-ag-done]').forEach(btn=>btn.onclick=()=>{const ev=db.group.agenda.find(x=>x.id===btn.dataset.agDone); if(ev){ev.status='hecho';ev.updatedAt=new Date().toISOString();saveDb();toast('Marcado como hecho');renderCurrentScreen();}}); document.querySelectorAll('[data-ag-del]').forEach(btn=>btn.onclick=()=>{if(!confirm('¿Eliminar este evento o recordatorio?'))return; db.group.agenda=db.group.agenda.filter(x=>x.id!==btn.dataset.agDel); saveDb(); toast('Evento eliminado'); renderCurrentScreen();}); }
function bindAgendaNotes(){ document.getElementById('quick-note-save')?.addEventListener('click',()=>{const text=valOf('quick-note-text').trim(); if(!text){toast('Escribe o dicta una nota');return;} ensureAgenda(); db.group.quickNotes.unshift(normalizeQuickNote({text,priority:valOf('quick-note-priority')})); saveDb(); toast('Nota guardada'); renderCurrentScreen();}); document.querySelectorAll('[data-note-del]').forEach(btn=>btn.onclick=()=>{db.group.quickNotes=db.group.quickNotes.filter(n=>n.id!==btn.dataset.noteDel);saveDb();toast('Nota eliminada');renderCurrentScreen();}); document.querySelectorAll('[data-note-to-reminder]').forEach(btn=>btn.onclick=()=>{const note=db.group.quickNotes.find(n=>n.id===btn.dataset.noteToReminder); if(!note)return; db.group.agenda.push(normalizeAgendaEvent({title:note.text.slice(0,70),type:'Recordatorio',date:today(),priority:note.priority,description:note.text})); db.group.quickNotes=db.group.quickNotes.filter(n=>n.id!==note.id); saveDb(); toast('Nota convertida en recordatorio'); agendaTab='week'; renderCurrentScreen();}); }
function bindAgendaTools(){ document.getElementById('ag-export-xlsx')?.addEventListener('click',exportAgendaExcel); document.getElementById('ag-export-json')?.addEventListener('click',exportAgendaJson); document.getElementById('ag-import-json')?.addEventListener('change',importAgendaJson); document.getElementById('ag-import-xlsx')?.addEventListener('change',importAgendaExcel); }
function exportAgendaExcel(){ ensureAgenda(); const rows=db.group.agenda.map(e=>({titulo:e.title,tipo:e.type,fecha:e.date,hora_inicio:e.startTime,hora_fin:e.endTime,prioridad:e.priority,repeticion:e.repeat,alumno:e.studentId?getStudentLabel(e.studentId):'',studentId:e.studentId,descripcion:e.description,estatus:e.status})); const wb=XLSX.utils.book_new(), ws=XLSX.utils.json_to_sheet(rows); styleSheet(ws); XLSX.utils.book_append_sheet(wb,ws,'AGENDA'); XLSX.writeFile(wb,`ProfeQr_Agenda_${db.config.group||'grupo'}.xlsx`); }
function exportAgendaJson(){ ensureAgenda(); downloadTextFile(`ProfeQr_Agenda_${db.config.group||'grupo'}.json`,JSON.stringify({agenda:db.group.agenda,quickNotes:db.group.quickNotes,exportedAt:new Date().toISOString()},null,2),'application/json;charset=utf-8'); }
function importAgendaJson(evt){ const file=evt.target.files?.[0]; if(!file)return; const r=new FileReader(); r.onload=()=>{try{const data=JSON.parse(r.result); if(!confirm('Importar agenda reemplazará eventos y notas actuales. ¿Continuar?'))return; db.group.agenda=(data.agenda||[]).map(normalizeAgendaEvent); db.group.quickNotes=(data.quickNotes||[]).map(normalizeQuickNote); saveDb(); toast('Agenda importada'); renderCurrentScreen();}catch(e){toast('JSON inválido');}}; r.readAsText(file); }
function importAgendaExcel(evt){ const file=evt.target.files?.[0]; if(!file)return; const r=new FileReader(); r.onload=ev=>{try{const data=new Uint8Array(ev.target.result); const wb=XLSX.read(data,{type:'array'}); const ws=wb.Sheets[wb.SheetNames[0]]; const rows=XLSX.utils.sheet_to_json(ws,{defval:''}); const imported=rows.map(row=>normalizeAgendaEvent({title:row.titulo||row.Titulo||row.title||'', type:row.tipo||row.Tipo||'Otro', date:String(row.fecha||row.Fecha||today()).slice(0,10), startTime:row.hora_inicio||row['Hora inicio']||'', endTime:row.hora_fin||row['Hora fin']||'', priority:row.prioridad||row.Prioridad||'media', repeat:row.repeticion||row.Repeticion||row.Repetición||'ninguna', studentId:row.studentId||'', description:row.descripcion||row.Descripcion||row.Descripción||'', status:row.estatus||row.Estatus||'pendiente'})).filter(e=>e.title&&e.date); if(!imported.length){toast('No se encontraron eventos válidos');return;} if(!confirm(`Importar ${imported.length} eventos y agregarlos a la agenda?`))return; db.group.agenda=[...imported,...(db.group.agenda||[])]; saveDb(); toast('Eventos importados'); renderCurrentScreen();}catch(e){console.error(e);toast('No se pudo importar Excel');}}; r.readAsArrayBuffer(file); }

