/* --- Biblioteca docente NEM --- */
let librarySectionFilter = 'Todas';
let libraryQuery = '';
let libraryEditingId = '';
function normalizeLibraryResource(r={}){
  const x = r && typeof r === 'object' ? {...r} : {};
  x.id = x.id || uid(); x.section = LIBRARY_SECTIONS.includes(x.section) ? x.section : 'Mi biblioteca'; x.title = x.title || ''; x.type = x.type || 'Nota'; x.tags = x.tags || ''; x.summary = x.summary || ''; x.content = x.content || ''; x.favorite = !!x.favorite; x.custom = x.custom !== false; x.createdAt = x.createdAt || new Date().toISOString(); x.updatedAt = x.updatedAt || x.createdAt; return x;
}
function ensureLibrary(){ db.group.libraryResources = Array.isArray(db.group.libraryResources) ? db.group.libraryResources.map(normalizeLibraryResource) : []; }
function libraryAllResources(){ ensureLibrary(); const customIds = new Set(db.group.libraryResources.map(r=>r.id)); const base = LIBRARY_DEFAULT_RESOURCES.filter(r=>!customIds.has(r.id)).map(r=>normalizeLibraryResource({...r,custom:false})); return [...base, ...db.group.libraryResources.map(normalizeLibraryResource)]; }
function libraryFilteredResources(){ const q = slug(libraryQuery); return libraryAllResources().filter(r=>{ const bySection = librarySectionFilter==='Todas' || r.section===librarySectionFilter; const hay = slug(`${r.title} ${r.section} ${r.type} ${r.tags} ${r.summary} ${r.content}`); return bySection && (!q || hay.includes(q)); }).sort((a,b)=> Number(b.favorite)-Number(a.favorite) || a.section.localeCompare(b.section) || a.title.localeCompare(b.title)); }
function renderLibrary(){
  if(libraryEditingId) return renderLibraryForm();
  const resources = libraryFilteredResources(); const favs = resources.filter(r=>r.favorite); const sections = ['Todas', ...LIBRARY_SECTIONS];
  return `<div class="card"><div class="section-title">Biblioteca docente</div><div class="help">Consulta rápida para NEM, planeación, CTE, normativa, protocolos y recursos de redacción. No sustituye la revisión de documentos oficiales.</div><div class="row" style="margin-top:10px"><input id="lib-search" value="${esc(libraryQuery)}" placeholder="Buscar: evaluación formativa, CTE, acoso, protocolo, acta..."><div class="tabs">${sections.map(sec=>`<button class="tab ${librarySectionFilter===sec?'active':''}" data-lib-sec="${esc(sec)}">${esc(sec)}</button>`).join('')}</div><div class="row row2"><button class="btn primary" id="lib-new">+ Recurso propio</button><button class="btn secondary" id="lib-export-json">Exportar biblioteca JSON</button></div><input id="lib-import-json" type="file" accept=".json" class="hidden"><button class="btn ghost" id="lib-import-trigger">Importar JSON</button></div></div>${favs.length?`<div class="card"><div class="section-title">Favoritos</div>${favs.slice(0,4).map(renderLibraryCard).join('')}</div>`:''}<div class="library-grid">${resources.length?resources.map(renderLibraryCard).join(''):'<div class="card"><div class="small">No hay recursos con ese filtro.</div></div>'}</div>`;
}
function renderLibraryCard(r){ const isCustom = r.custom !== false; return `<div class="library-card card"><div class="library-top"><span class="badge primary">${esc(r.section)}</span><button class="mini" data-lib-fav="${esc(r.id)}">${r.favorite?'★':'☆'}</button></div><div class="item-title" style="font-size:16px;margin-top:8px">${esc(r.title||'Sin título')}</div><div class="item-sub">${esc(r.type)}${r.tags?' · '+esc(r.tags):''}</div>${r.summary?`<div class="help">${esc(r.summary)}</div>`:''}<details class="library-details"><summary>Ver contenido</summary><div class="library-content">${esc(r.content||'Sin contenido.').replace(/\n/g,'<br>')}</div></details><div class="agenda-actions" style="margin-top:10px">${isCustom?`<button class="mini" data-lib-edit="${esc(r.id)}">Editar</button><button class="mini" data-lib-del="${esc(r.id)}">Eliminar</button>`:''}<button class="mini" data-lib-copy="${esc(r.id)}">Copiar texto</button></div></div>`; }
function renderLibraryForm(){ const current = db.group.libraryResources.find(r=>r.id===libraryEditingId) || normalizeLibraryResource({section:'Mi biblioteca',custom:true}); return `<div class="card"><div class="section-title">${libraryEditingId==='new'?'Nuevo recurso':'Editar recurso'}</div><div class="row"><div><div class="small">Sección</div><select id="lib-f-section">${LIBRARY_SECTIONS.map(sec=>`<option value="${esc(sec)}" ${current.section===sec?'selected':''}>${esc(sec)}</option>`).join('')}</select></div><div><div class="small">Título</div><input id="lib-f-title" value="${esc(current.title)}" placeholder="Ej. Evaluación formativa"></div><div><div class="small">Tipo</div><select id="lib-f-type">${['Guía rápida','Normativa','Protocolo','Formato guía','Banco de frases','Nota','Otro'].map(t=>`<option ${current.type===t?'selected':''}>${t}</option>`).join('')}</select></div><div><div class="small">Etiquetas</div><input id="lib-f-tags" value="${esc(current.tags)}" placeholder="palabras clave separadas por coma"></div><div><div class="small">Resumen</div><textarea id="lib-f-summary" rows="3" placeholder="Resumen breve">${esc(current.summary)}</textarea>${micBtn('lib-f-summary')}</div><div><div class="small">Contenido</div><textarea id="lib-f-content" rows="8" placeholder="Texto, formato, recordatorio normativo o recurso propio">${esc(current.content)}</textarea>${micBtn('lib-f-content')}</div><label class="check-line"><input id="lib-f-fav" type="checkbox" ${current.favorite?'checked':''}> Marcar como favorito</label><div class="row row2"><button class="btn secondary" id="lib-cancel">Cancelar</button><button class="btn primary" id="lib-save">Guardar recurso</button></div></div></div>`; }
function bindLibrary(){ bindMicButtons(); document.getElementById('lib-search')?.addEventListener('input',e=>{libraryQuery=e.target.value;renderCurrentScreen();}); document.querySelectorAll('[data-lib-sec]').forEach(btn=>btn.onclick=()=>{librarySectionFilter=btn.dataset.libSec;renderCurrentScreen();}); document.getElementById('lib-new')?.addEventListener('click',()=>{libraryEditingId='new';renderCurrentScreen();}); document.getElementById('lib-export-json')?.addEventListener('click',exportLibraryJson); document.getElementById('lib-import-trigger')?.addEventListener('click',()=>document.getElementById('lib-import-json')?.click()); document.getElementById('lib-import-json')?.addEventListener('change',importLibraryJson); document.querySelectorAll('[data-lib-fav]').forEach(btn=>btn.onclick=()=>toggleLibraryFavorite(btn.dataset.libFav)); document.querySelectorAll('[data-lib-edit]').forEach(btn=>btn.onclick=()=>{libraryEditingId=btn.dataset.libEdit;renderCurrentScreen();}); document.querySelectorAll('[data-lib-del]').forEach(btn=>btn.onclick=()=>deleteLibraryResource(btn.dataset.libDel)); document.querySelectorAll('[data-lib-copy]').forEach(btn=>btn.onclick=()=>copyLibraryResource(btn.dataset.libCopy)); document.getElementById('lib-cancel')?.addEventListener('click',()=>{libraryEditingId='';renderCurrentScreen();}); document.getElementById('lib-save')?.addEventListener('click',saveLibraryResource); }
function saveLibraryResource(){ ensureLibrary(); const id = libraryEditingId && libraryEditingId!=='new' ? libraryEditingId : uid(); const previous = db.group.libraryResources.find(r=>r.id===id); const item = normalizeLibraryResource({id, section:valOf('lib-f-section'), title:valOf('lib-f-title').trim(), type:valOf('lib-f-type'), tags:valOf('lib-f-tags').trim(), summary:valOf('lib-f-summary').trim(), content:valOf('lib-f-content').trim(), favorite:document.getElementById('lib-f-fav')?.checked || false, custom:true, createdAt:previous?.createdAt || new Date().toISOString(), updatedAt:new Date().toISOString()}); if(!item.title){toast('El título es obligatorio');return;} const idx=db.group.libraryResources.findIndex(r=>r.id===id); if(idx>=0) db.group.libraryResources[idx]=item; else db.group.libraryResources.push(item); if(!saveDb()) return; libraryEditingId=''; toast('Recurso guardado'); renderCurrentScreen(); }
function toggleLibraryFavorite(id){ ensureLibrary(); let item=db.group.libraryResources.find(r=>r.id===id); if(!item){ const base=LIBRARY_DEFAULT_RESOURCES.find(r=>r.id===id); if(base){ item=normalizeLibraryResource({...base,custom:false,favorite:!base.favorite}); db.group.libraryResources.push(item); } } else item.favorite=!item.favorite; saveDb(); renderCurrentScreen(); }
function deleteLibraryResource(id){ if(!confirm('¿Eliminar este recurso propio de la biblioteca?')) return; db.group.libraryResources=(db.group.libraryResources||[]).filter(r=>r.id!==id); saveDb(); toast('Recurso eliminado'); renderCurrentScreen(); }
function copyLibraryResource(id){ const r=libraryAllResources().find(x=>x.id===id); if(!r)return; const text=`${r.title}\n\n${r.summary||''}\n\n${r.content||''}`; if(navigator.clipboard?.writeText){ navigator.clipboard.writeText(text).then(()=>toast('Texto copiado')).catch(()=>downloadTextFile('recurso_biblioteca.txt',text,'text/plain;charset=utf-8')); } else downloadTextFile('recurso_biblioteca.txt',text,'text/plain;charset=utf-8'); }
function exportLibraryJson(){ ensureLibrary(); downloadTextFile(`ProfeQr_Biblioteca_${today()}.json`, JSON.stringify({libraryResources:db.group.libraryResources, exportedAt:new Date().toISOString()}, null, 2), 'application/json;charset=utf-8'); }
function importLibraryJson(evt){ const file=evt.target.files?.[0]; if(!file)return; const r=new FileReader(); r.onload=()=>{try{const data=JSON.parse(r.result); const arr=Array.isArray(data.libraryResources)?data.libraryResources:Array.isArray(data)?data:[]; if(!arr.length){toast('No se encontraron recursos');return;} if(!confirm(`Importar ${arr.length} recursos a Mi biblioteca?`))return; ensureLibrary(); db.group.libraryResources=[...arr.map(x=>normalizeLibraryResource({...x,custom:true})), ...db.group.libraryResources]; saveDb(); toast('Biblioteca importada'); renderCurrentScreen();}catch(e){toast('JSON inválido');}}; r.readAsText(file); }

