-- ProfeQr / Direkta — Etapa 3: comunicación, roles y auditoría
create extension if not exists pgcrypto;

create table if not exists public.school_actor_keys (
  id uuid primary key default gen_random_uuid(),
  school_id text not null,
  actor_id text not null,
  actor_name text not null default '',
  actor_role text not null check (actor_role in ('director','teacher','paee')),
  group_name text,
  token_hash text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (school_id, actor_id)
);
alter table public.school_actor_keys enable row level security;

create or replace function public.request_actor(requested_school text)
returns jsonb language sql stable security definer set search_path=public as $$
  select jsonb_build_object('id',k.actor_id,'name',k.actor_name,'role',k.actor_role,'group',k.group_name)
  from public.school_actor_keys k
  where k.school_id=requested_school and k.active
    and k.token_hash=encode(digest(coalesce((current_setting('request.headers',true)::jsonb->>'x-school-token'),''),'sha256'),'hex')
  limit 1;
$$;
revoke all on function public.request_actor(text) from public;
grant execute on function public.request_actor(text) to anon,authenticated;

create or replace function public.school_request_authorized(requested_school text)
returns boolean language sql stable security definer set search_path=public as $$
  select public.request_actor(requested_school) is not null;
$$;

create table if not exists public.school_notices (
  id uuid primary key default gen_random_uuid(), school_id text not null,
  title text not null check (length(title) between 1 and 140),
  body text not null check (length(body) between 1 and 2000),
  audience_type text not null default 'all' check (audience_type in ('all','group','teacher')),
  audience_value text, priority text not null default 'normal' check (priority in ('normal','high')),
  created_by text not null, published_at timestamptz not null default now(), expires_at timestamptz
);
create index if not exists idx_school_notices_school_date on public.school_notices(school_id,published_at desc);

create table if not exists public.notice_reads (
  school_id text not null, notice_id uuid not null references public.school_notices(id) on delete cascade,
  teacher_id text not null, read_at timestamptz not null default now(), primary key(notice_id,teacher_id)
);

create table if not exists public.school_messages (
  id uuid primary key default gen_random_uuid(), school_id text not null,
  kind text not null check (kind in ('incident','request')),
  category text not null, group_name text not null, teacher_id text not null, teacher_name text not null default '',
  body text not null check (length(body) between 1 and 800), priority text not null default 'normal' check(priority in ('normal','high')),
  status text not null default 'new' check(status in ('new','received','in_process','resolved','rejected')),
  director_response text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists idx_school_messages_inbox on public.school_messages(school_id,status,created_at desc);

create table if not exists public.communication_audit (
  id bigint generated by default as identity primary key, school_id text not null,
  entity_type text not null, entity_id text not null, action text not null,
  actor_id text not null, actor_role text not null, details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_communication_audit_school_date on public.communication_audit(school_id,created_at desc);

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(), school_id text not null, actor_id text not null,
  endpoint text not null, p256dh text not null, auth text not null, user_agent text,
  active boolean not null default true, updated_at timestamptz not null default now(),
  unique(school_id,actor_id,endpoint)
);

alter table public.school_notices enable row level security;
alter table public.notice_reads enable row level security;
alter table public.school_messages enable row level security;
alter table public.communication_audit enable row level security;
alter table public.push_subscriptions enable row level security;

drop policy if exists attendance_reports_actor_read on public.attendance_reports;
drop policy if exists attendance_reports_teacher_insert on public.attendance_reports;
drop policy if exists attendance_reports_teacher_update on public.attendance_reports;
drop policy if exists notices_target_read on public.school_notices;
drop policy if exists notices_director_write on public.school_notices;
drop policy if exists reads_owner_select on public.notice_reads;
drop policy if exists reads_owner_insert on public.notice_reads;
drop policy if exists reads_owner_update on public.notice_reads;
drop policy if exists messages_participant_read on public.school_messages;
drop policy if exists messages_teacher_insert on public.school_messages;
drop policy if exists messages_director_update on public.school_messages;
drop policy if exists audit_director_read on public.communication_audit;
drop policy if exists push_owner_select on public.push_subscriptions;
drop policy if exists push_owner_insert on public.push_subscriptions;
drop policy if exists push_owner_update on public.push_subscriptions;

drop policy if exists attendance_reports_school_read on public.attendance_reports;
drop policy if exists attendance_reports_school_insert on public.attendance_reports;
drop policy if exists attendance_reports_school_update on public.attendance_reports;
create policy attendance_reports_actor_read on public.attendance_reports for select to anon,authenticated using (
  public.school_request_authorized(school_id) and ((public.request_actor(school_id)->>'role')='director' or ((public.request_actor(school_id)->>'role')='teacher' and (public.request_actor(school_id)->>'group')=group_name))
);
create policy attendance_reports_teacher_insert on public.attendance_reports for insert to anon,authenticated with check (
  public.school_request_authorized(school_id) and (public.request_actor(school_id)->>'role')='teacher' and (public.request_actor(school_id)->>'id')=teacher_id and (public.request_actor(school_id)->>'group')=group_name
);
create policy attendance_reports_teacher_update on public.attendance_reports for update to anon,authenticated using (
  public.school_request_authorized(school_id) and (public.request_actor(school_id)->>'role')='teacher' and (public.request_actor(school_id)->>'id')=teacher_id and (public.request_actor(school_id)->>'group')=group_name
) with check ((public.request_actor(school_id)->>'id')=teacher_id and (public.request_actor(school_id)->>'group')=group_name);

create policy notices_target_read on public.school_notices for select to anon,authenticated using (
  public.school_request_authorized(school_id) and ((public.request_actor(school_id)->>'role')='director' or audience_type='all' or (audience_type='group' and audience_value=(public.request_actor(school_id)->>'group')) or (audience_type='teacher' and audience_value=(public.request_actor(school_id)->>'id')))
);
create policy notices_director_write on public.school_notices for insert to anon,authenticated with check ((public.request_actor(school_id)->>'role')='director' and created_by=(public.request_actor(school_id)->>'id'));

create policy reads_owner_select on public.notice_reads for select to anon,authenticated using ((public.request_actor(school_id)->>'role')='director' or teacher_id=(public.request_actor(school_id)->>'id'));
create policy reads_owner_insert on public.notice_reads for insert to anon,authenticated with check (teacher_id=(public.request_actor(school_id)->>'id'));
create policy reads_owner_update on public.notice_reads for update to anon,authenticated using (teacher_id=(public.request_actor(school_id)->>'id')) with check (teacher_id=(public.request_actor(school_id)->>'id'));

create policy messages_participant_read on public.school_messages for select to anon,authenticated using ((public.request_actor(school_id)->>'role')='director' or teacher_id=(public.request_actor(school_id)->>'id'));
create policy messages_teacher_insert on public.school_messages for insert to anon,authenticated with check ((public.request_actor(school_id)->>'role')='teacher' and teacher_id=(public.request_actor(school_id)->>'id') and group_name=(public.request_actor(school_id)->>'group'));
create policy messages_director_update on public.school_messages for update to anon,authenticated using ((public.request_actor(school_id)->>'role')='director') with check ((public.request_actor(school_id)->>'role')='director');
create policy audit_director_read on public.communication_audit for select to anon,authenticated using ((public.request_actor(school_id)->>'role')='director');
create policy push_owner_select on public.push_subscriptions for select to anon,authenticated using (actor_id=(public.request_actor(school_id)->>'id'));
create policy push_owner_insert on public.push_subscriptions for insert to anon,authenticated with check (actor_id=(public.request_actor(school_id)->>'id'));
create policy push_owner_update on public.push_subscriptions for update to anon,authenticated using (actor_id=(public.request_actor(school_id)->>'id')) with check (actor_id=(public.request_actor(school_id)->>'id'));

create or replace function public.audit_school_change() returns trigger language plpgsql security definer set search_path=public as $$
declare school text:=coalesce(new.school_id,old.school_id); actor jsonb; entity text:=tg_table_name; eid text;
begin actor:=public.request_actor(school);eid:=coalesce(new.id::text,old.id::text);insert into public.communication_audit(school_id,entity_type,entity_id,action,actor_id,actor_role,details) values(school,entity,eid,tg_op,coalesce(actor->>'id','system'),coalesce(actor->>'role','system'),jsonb_build_object('new',to_jsonb(new),'old',to_jsonb(old)));if tg_op='DELETE' then return old;else return new;end if;end;$$;
drop trigger if exists audit_school_notices on public.school_notices;
drop trigger if exists audit_school_messages on public.school_messages;
create trigger audit_school_notices after insert or update or delete on public.school_notices for each row execute function public.audit_school_change();
create trigger audit_school_messages after insert or update or delete on public.school_messages for each row execute function public.audit_school_change();

-- Sustituye todos los tokens antes de ejecutar. Cada dispositivo debe recibir sólo su token.
insert into public.school_actor_keys(school_id,actor_id,actor_name,actor_role,group_name,token_hash) values
('11DTV0020P','direccion','Dirección','director',null,encode(digest('CAMBIAR-TOKEN-DIRECCION','sha256'),'hex')),
('11DTV0020P','rodriguez-1g','Soraya E. Rodríguez','teacher','1°G',encode(digest('CAMBIAR-TOKEN-1G','sha256'),'hex')),
('11DTV0020P','rivas-1h','Carlos R. Rivas','teacher','1°H',encode(digest('CAMBIAR-TOKEN-1H','sha256'),'hex')),
('11DTV0020P','murillo-2g','Alejandro Murillo','teacher','2°G',encode(digest('CAMBIAR-TOKEN-2G','sha256'),'hex')),
('11DTV0020P','martinez-2h','Octavio Natanael Martínez','teacher','2°H',encode(digest('CAMBIAR-TOKEN-2H','sha256'),'hex')),
('11DTV0020P','arcos-3g','María Luisa Arcos','teacher','3°G',encode(digest('CAMBIAR-TOKEN-3G','sha256'),'hex')),
('11DTV0020P','perez-3h','Irving Aloi Pérez','teacher','3°H',encode(digest('CAMBIAR-TOKEN-3H','sha256'),'hex'))
on conflict(school_id,actor_id) do update set actor_name=excluded.actor_name,actor_role=excluded.actor_role,group_name=excluded.group_name,token_hash=excluded.token_hash,active=true;
