-- ProfeQr / Direkta attendance sync
create table if not exists public.attendance_reports (
  id bigint generated by default as identity primary key,
  school_id text not null,
  report_date date not null,
  group_name text not null,
  teacher_id text not null,
  teacher_name text default '',
  total_students integer not null default 0,
  present_count integer not null default 0,
  absent_count integer not null default 0,
  absences jsonb not null default '[]'::jsonb,
  captured_at timestamptz not null default now(),
  app text not null default 'ProfeQr',
  updated_at timestamptz not null default now(),
  unique (school_id, report_date, group_name)
);

create index if not exists idx_attendance_reports_school_date
  on public.attendance_reports (school_id, report_date desc);

alter table public.attendance_reports enable row level security;

-- MVP policy. Replace with authenticated-user policies before multi-school sale.
drop policy if exists "attendance_reports_anon_read" on public.attendance_reports;
create policy "attendance_reports_anon_read"
  on public.attendance_reports for select to anon using (true);

drop policy if exists "attendance_reports_anon_insert" on public.attendance_reports;
create policy "attendance_reports_anon_insert"
  on public.attendance_reports for insert to anon with check (true);

drop policy if exists "attendance_reports_anon_update" on public.attendance_reports;
create policy "attendance_reports_anon_update"
  on public.attendance_reports for update to anon using (true) with check (true);

comment on table public.attendance_reports is 'Daily group attendance reports sent from ProfeQr and consumed by Direkta.';
