-- ProfeQr / Direkta attendance sync — Etapa 2
create extension if not exists pgcrypto;

create table if not exists public.school_sync_keys (
  school_id text primary key,
  token_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.attendance_reports (
  id bigint generated by default as identity primary key,
  school_id text not null,
  report_date date not null,
  group_name text not null,
  teacher_id text not null,
  teacher_name text default '',
  total_students integer not null default 0 check (total_students >= 0),
  present_count integer not null default 0 check (present_count >= 0),
  absent_count integer not null default 0 check (absent_count >= 0),
  absences jsonb not null default '[]'::jsonb,
  revision integer not null default 1 check (revision > 0),
  captured_at timestamptz not null default now(),
  app text not null default 'ProfeQr',
  updated_at timestamptz not null default now(),
  unique (school_id, report_date, group_name),
  check (present_count + absent_count = total_students),
  check (jsonb_typeof(absences) = 'array')
);

alter table public.attendance_reports add column if not exists revision integer not null default 1;
create index if not exists idx_attendance_reports_school_date on public.attendance_reports (school_id, report_date desc);

create or replace function public.school_request_authorized(requested_school text)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.school_sync_keys k
    where k.school_id = requested_school and k.active
      and k.token_hash = encode(digest(coalesce((current_setting('request.headers', true)::jsonb ->> 'x-school-token'), ''), 'sha256'), 'hex')
  );
$$;

revoke all on function public.school_request_authorized(text) from public;
grant execute on function public.school_request_authorized(text) to anon, authenticated;
alter table public.school_sync_keys enable row level security;
alter table public.attendance_reports enable row level security;

drop policy if exists "attendance_reports_anon_read" on public.attendance_reports;
drop policy if exists "attendance_reports_anon_insert" on public.attendance_reports;
drop policy if exists "attendance_reports_anon_update" on public.attendance_reports;
drop policy if exists "attendance_reports_school_read" on public.attendance_reports;
drop policy if exists "attendance_reports_school_insert" on public.attendance_reports;
drop policy if exists "attendance_reports_school_update" on public.attendance_reports;

create policy "attendance_reports_school_read" on public.attendance_reports for select to anon, authenticated
  using (public.school_request_authorized(school_id));
create policy "attendance_reports_school_insert" on public.attendance_reports for insert to anon, authenticated
  with check (public.school_request_authorized(school_id));
create policy "attendance_reports_school_update" on public.attendance_reports for update to anon, authenticated
  using (public.school_request_authorized(school_id)) with check (public.school_request_authorized(school_id));

-- Cambia el token antes de ejecutar y guárdalo sólo en dispositivos autorizados.
insert into public.school_sync_keys (school_id, token_hash)
values ('11DTV0020P', encode(digest('CAMBIAR-POR-UNA-CLAVE-LARGA', 'sha256'), 'hex'))
on conflict (school_id) do update set token_hash = excluded.token_hash, active = true;

comment on table public.attendance_reports is 'Daily group reports with stable student IDs for Direkta history and alerts.';
